openapi: 3.0.2
info:
    title: gin-api
    version: openapi.v3
    description: gin-api
    contact:
        name: yinsiyu
servers:
    -
        url: 'http://0.0.0.0:8849/api'
        description: ''
paths:
    /test/hello:
        get:
            tags:
                - test
            parameters:
                -
                    name: value
                    description: ''
                    schema:
                        type: integer
                    in: query
                    required: false
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CommonResponse'
                    description: 请求成功
            operationId: Say
components:
    schemas:
        CommonResponse:
            description: ''
            required:
                - message
                - status
            type: object
            properties:
                message:
                    description: ''
                    type: string
                status:
                    $ref: '#/components/schemas/ResponseStatus'
                    description: ''
        ResponseStatus:
            description: ''
            enum:
                - success
                - fail
                - error
            type: string
tags:
    -
        name: test
        description: 测试用接口
