/*
 * gin-api
 *
 * gin-api
 *
 * API version: openapi.v3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type TestAPI struct {
	// Get /api/test/hello
	// 
	Say gin.HandlerFunc
}
